project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  title: "EMU Hacettepe"
  navbar:
    left:
      - href: index.qmd
        text: Giriş
      - href: company.qmd
        text: Türk Traktör
      - href: scope.qmd
        text: Proje Kapsamı
      - href: method.qmd
        text: Metodoloji
      - href: analysis.qmd
        text: Uygulama
      - href: result.qmd
        text: Sonuç

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

