project:
  type: website
  output-dir: docs

website:
  title: "EMU Hacettepe"
  navbar:
    left:
      - href: index.qmd
        text: Giriş
      - href: about.qmd
        text: Hakkımızda

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

