---
styles:
  styles.css
format:
  html:
    title: 'TLB İş Makineleri Montaj Hattı Optimizasyonu'
---

Hacettepe Endüstri Mühendisliği bitirme projesi sayfamıza hoş geldiniz.

## Proje Takımımız

[Mert Bekir Kaplan](https://emu-hacettepe-analytics.github.io/emu430-fall2023-mer7kaplan/){.download-button} [Zümrüt Zeynep Özsoy](https://emu-hacettepe-analytics.github.io/emu430-fall2023-zzeynepo/){.download-button} [Gülin Ünsal](https://emu-hacettepe-analytics.github.io/emu430-fall2023-gulinunsal/){.download-button} [Arda Türkan](https://emu-hacettepe-analytics.github.io/emu430-fall2023-ardaturkan/){.download-button}

## Proje Özeti

::: {style="text-align: justify;"}
Türk Traktör'de kullanılan TLB iş makinelerinin montaj hattı şu anda en verimli şekilde çalışmıyor. Bu projenin temel hedefleri montaj hattının verimliliğini artırmak ve iyileştirmektir. Bunu hatların planlanması ve dengelenmesiyle gerçekleştirmeyi amaçlıyoruz. Bu sorunları çözmek için montaj sürecindeki sorunları sistematik olarak tanımlamaya, araştırmaya ve düzeltmeye çalışıyoruz.Buluşsal yöntemler, yalın üretim, simülasyon ve değer akışı haritalaması gibi çeşitli yaklaşımlarla bu sorunları çözmeye ve iyileştirmeler yapmaya çalışıyoruz. Bu yöntemlerin birleşimi, montaj hattının mevcut durumunun kapsamlı bir analizini kolaylaştıracak ve etkili çözümler geliştirmemize yardımcı olacaktır. Böylelikle hangi istasyonların iyileştirilmesi gerektiğini tespit edip simülasyon kullanarak yeni bir tasarım oluşturabiliyoruz.
:::
